-- CreateEnum
CREATE TYPE "StatusPedido" AS ENUM ('RECEBIDO', 'EM_PROCESSAMENTO', 'CONCLUIDO', 'CANCELADO');

-- AlterTable
ALTER TABLE "Pedido" ADD COLUMN     "atualizado_em" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "status" "StatusPedido" NOT NULL DEFAULT 'RECEBIDO';
