import { test, expect, type Page } from "@playwright/test"
import AxeBuilder from "@axe-core/playwright"
import path from "node:path"

async function login(page: Page, email: string) {
  await page.locator(".profile-trigger").click()
  const modal = page.getByRole("dialog")
  if (await modal.getByRole("button", { name: "Adicionar outro perfil" }).isVisible())
    await modal.getByRole("button", { name: "Adicionar outro perfil" }).click()
  await modal.getByLabel("Email", { exact: true }).fill(email)
  await modal.getByLabel("Senha", { exact: true }).fill("OrbitaDemo2026!")
  await modal.getByRole("button", { name: "Entrar na minha conta" }).click()
  await expect(modal).not.toBeVisible()
}
test("catálogo, busca, filtros, acessibilidade e layout móvel", async ({ page }) => {
  const errors: string[] = []
  page.on("pageerror", (error) => errors.push(error.message))
  await page.goto("/")
  await expect(page.locator(".product-card")).toHaveCount(8)
  await expect(page.getByRole("heading", { level: 1 })).toContainText("Coisas boas")
  const desktopA11y = await new AxeBuilder({ page })
    .withTags(["wcag2a", "wcag2aa", "wcag21aa"])
    .analyze()
  expect(desktopA11y.violations).toEqual([])
  await page.screenshot({ path: "artifacts/home-desktop.png", fullPage: true })
  await page.getByRole("searchbox", { name: "Buscar produtos" }).fill("Headphone")
  await page.getByRole("button", { name: "Pesquisar", exact: true }).click()
  await expect(page.locator(".product-card")).toHaveCount(1)
  await expect(page.locator(".product-card")).toContainText("Headphone Studio Wireless")
  await page.getByRole("button", { name: "Limpar filtros" }).click()
  await page.getByRole("button", { name: "Casa & design", exact: true }).click()
  await expect(page.locator(".product-card")).toHaveCount(3)
  await page.getByRole("combobox", { name: "Ordenar por" }).selectOption("menor-preco")
  await expect(page.locator(".product-card").first()).toContainText("Vaso Botânico")
  await page.getByLabel("Máximo", { exact: true }).fill("100")
  await page.getByRole("button", { name: "Aplicar preço" }).click()
  await expect(page.locator(".product-card")).toHaveCount(1)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/")
  await expect(page.locator(".product-card")).toHaveCount(8)
  await page.screenshot({ path: "artifacts/home-mobile.png", fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
  const mobileA11y = await new AxeBuilder({ page })
    .withTags(["wcag2a", "wcag2aa", "wcag21aa"])
    .analyze()
  expect(mobileA11y.violations).toEqual([])
  await page.getByRole("button", { name: "Abrir navegação" }).click()
  await expect(page.getByRole("navigation", { name: "Navegação principal" })).toBeVisible()
  expect(errors).toEqual([])
})

test("compra com dois vendedores, cancelamento, entrega e troca persistente de perfis", async ({
  page,
}) => {
  await page.goto("/")
  await page.locator(".profile-trigger").click()
  const dialog = page.getByRole("dialog")
  await dialog.getByRole("button", { name: "Criar conta", exact: true }).click()
  await dialog.getByLabel("Seu nome").fill("Cliente Navegador")
  await dialog.getByLabel("Email", { exact: true }).fill(`cliente-${Date.now()}@example.test`)
  await dialog.getByLabel("Senha", { exact: true }).fill("SenhaNavegador2026!")
  await dialog.getByRole("button", { name: "Criar minha conta" }).click()
  await expect(dialog).not.toBeVisible()
  for (const id of [
    "10000000-0000-4000-8000-000000000001",
    "10000000-0000-4000-8000-000000000005",
  ]) {
    await page.goto(`/produto/${id}`)
    await page.getByRole("button", { name: "Adicionar ao carrinho" }).click()
    await expect(page.getByRole("link", { name: "Ver meu carrinho" })).toBeVisible()
  }
  await page.getByRole("link", { name: "Ver meu carrinho" }).click()
  await expect(page.locator(".cart-group")).toHaveCount(2)
  await expect(page.locator(".summary-total")).toContainText("539,80")
  const cartA11y = await new AxeBuilder({ page })
    .withTags(["wcag2a", "wcag2aa", "wcag21aa"])
    .analyze()
  expect(cartA11y.violations).toEqual([])
  await page.screenshot({ path: "artifacts/cart-desktop.png", fullPage: true })
  await page.getByRole("button", { name: "Continuar para entrega" }).click()
  await page.getByLabel("CEP", { exact: true }).fill("01001000")
  await page.getByLabel("Número", { exact: true }).fill("123")
  await page.getByLabel("Rua ou avenida").fill("Rua de Demonstração")
  await page.getByLabel("Cidade", { exact: true }).fill("São Paulo")
  await page.getByRole("combobox", { name: "Estado", exact: true }).selectOption("SP")
  await page.getByRole("button", { name: "Finalizar compra simulada" }).click()
  await expect(
    page.getByRole("heading", { name: "Seus achados já estão na sua órbita!" }),
  ).toBeVisible()
  await expect(page.locator(".order-card")).toHaveCount(2)
  const forma = page.locator(".order-card").filter({ hasText: "Forma & Casa" })
  await forma.getByRole("button", { name: "Cancelar pedido", exact: true }).click()
  await page.getByRole("button", { name: "Confirmar cancelamento" }).click()
  await expect(forma.locator(".status")).toHaveText("Cancelado")
  await expect(forma).toContainText("Estorno simulado")
  await login(page, "nova@orbita.demo")
  await expect(page.getByRole("heading", { name: "Nova Studio." })).toBeVisible()
  await page.getByRole("button", { name: "Preparar pedido", exact: true }).click()
  await page.getByRole("button", { name: "Marcar como enviado" }).click()
  await page.getByRole("button", { name: "Confirmar entrega" }).click()
  await expect(page.locator(".order-card .status")).toHaveText("Entregue")
  await page.screenshot({ path: "artifacts/seller-desktop.png", fullPage: true })
  const sellerA11y = await new AxeBuilder({ page })
    .withTags(["wcag2a", "wcag2aa", "wcag21aa"])
    .analyze()
  expect(sellerA11y.violations).toEqual([])
  await page.reload()
  await page.locator(".profile-trigger").click()
  await expect(page.locator(".profile-row")).toHaveCount(2)
  await page.getByRole("button", { name: /Cliente Navegador Comprador/ }).click()
  await page.goto("/compras")
  await expect(
    page.locator(".order-card").filter({ hasText: "Nova Studio" }).locator(".status"),
  ).toHaveText("Entregue")
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
  await page.screenshot({ path: "artifacts/orders-mobile.png", fullPage: true })
})

test("vendedor publica foto, edita estoque e pausa um anúncio", async ({ page }) => {
  await page.goto("/")
  await login(page, "movimento@orbita.demo")
  await page.getByRole("button", { name: "Meus produtos", exact: true }).click()
  await page.getByRole("button", { name: "Novo produto", exact: true }).click()
  const dialog = page.getByRole("dialog")
  await dialog
    .getByLabel("Foto do produto")
    .setInputFiles(path.resolve("frontend/public/images/headphones.jpg"))
  await expect(dialog.getByAltText("Prévia da imagem do produto")).toBeVisible()
  await dialog.getByLabel("Nome do produto").fill("Produto Publicado no Navegador")
  await dialog
    .getByLabel("Descrição", { exact: true })
    .fill("Um produto publicado e testado através de um navegador real.")
  await dialog.getByRole("combobox", { name: "Categoria", exact: true }).selectOption("tecnologia")
  await dialog.getByLabel("Preço (R$)", { exact: true }).fill("199.90")
  await dialog.getByLabel("Unidades em estoque").fill("7")
  await dialog.getByRole("button", { name: "Publicar produto", exact: true }).click()
  await expect(dialog).not.toBeVisible()
  const row = page.getByRole("row").filter({ hasText: "Produto Publicado no Navegador" })
  await expect(row).toContainText("199,90")
  await expect(row).toContainText("7 un.")
  await row.getByRole("button", { name: "Editar Produto Publicado no Navegador" }).click()
  await dialog.getByLabel("Unidades em estoque").fill("3")
  await dialog.getByLabel("Publicar na vitrine").uncheck()
  await dialog.getByRole("button", { name: "Salvar alterações", exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(row).toContainText("Pausado")
  await expect(row).toContainText("3 un.")
  await page.goto("/explorar?busca=Produto%20Publicado%20no%20Navegador")
  await expect(
    page.getByRole("heading", { name: "Ainda não encontramos esse achado." }),
  ).toBeVisible()
})
